"""Create the initial schema

On a database that already holds every table, upgrade() records the revision and
creates nothing; `alembic stamp head` has the same effect. A database holding only
some of them stops the migration.

Revision ID: 658616cf0c2b
Revises:
Create Date: 2026-08-14 21:17:23.220030

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "658616cf0c2b"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

TABLES = {
    "draft_series",
    "fantasy_bets",
    "fantasy_team_player",
    "fantasy_teams",
    "koth_events",
    "koth_match_participants",
    "koth_matches",
    "koth_signups",
    "map_season",
    "maps",
    "matches",
    "player_career_stats",
    "seasons",
    "series",
    "settings",
    "team_season",
    "teams",
    "user_season_signup",
    "user_team_season",
    "users",
    "w3cstats",
}


def upgrade() -> None:
    present = TABLES & set(sa.inspect(op.get_bind()).get_table_names())
    if present == TABLES:
        return
    if present:
        raise RuntimeError(
            "The database holds some of the tables of this revision but not "
            f"all of them. Missing: {sorted(TABLES - present)}. Fix the "
            "database by hand, then run `alembic stamp head`."
        )

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "koth_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.Column("event_date", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("bracket_1_threshold", sa.Integer(), nullable=False),
        sa.Column("bracket_2_threshold", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_koth_events")),
        mysql_charset="utf8mb4",
    )
    op.create_table(
        "maps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column(
            "shortname", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.Column("image", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_maps")),
    )
    op.create_table(
        "seasons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("number_weeks", sa.Integer(), nullable=False),
        sa.Column("series_per_week", sa.Integer(), nullable=False),
        sa.Column(
            "pick_ban", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "discordRole", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_seasons")),
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "value", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
    )
    op.create_index(op.f("ix_settings_key"), "settings", ["key"], unique=True)
    op.create_table(
        "teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "long_name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True
        ),
        sa.Column("icon", sa.LargeBinary(), nullable=True),
        sa.Column(
            "discord_role", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column(
            "battleTag", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "discordTag", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "discordId", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "race",
            sa.Enum("RANDOM", "HU", "OC", "NE", "UD", name="race"),
            nullable=False,
        ),
        sa.Column("mmr", sa.Integer(), nullable=True),
        sa.Column("country", sqlmodel.sql.sqltypes.AutoString(length=2), nullable=True),
        sa.Column("fantasy_tier", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        mysql_charset="utf8mb4",
    )
    op.create_table(
        "fantasy_teams",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("captain_id", sa.Integer(), nullable=False),
        sa.Column("drafted_team_id", sa.Integer(), nullable=True),
        sa.Column(
            "drafted_race",
            sa.Enum("RANDOM", "HU", "OC", "NE", "UD", name="race"),
            nullable=True,
        ),
        sa.Column("player_points", sa.Integer(), nullable=True),
        sa.Column("bench_points", sa.Integer(), nullable=True),
        sa.Column("team_points", sa.Integer(), nullable=True),
        sa.Column("race_points", sa.Integer(), nullable=True),
        sa.Column("bet_points", sa.Integer(), nullable=True),
        sa.Column("total_points", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["captain_id"],
            ["users.id"],
            ondelete="CASCADE",
            name=op.f("fk_fantasy_teams_captain_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["drafted_team_id"],
            ["teams.id"],
            ondelete="CASCADE",
            name=op.f("fk_fantasy_teams_drafted_team_id_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            ondelete="CASCADE",
            name=op.f("fk_fantasy_teams_season_id_seasons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fantasy_teams")),
    )
    op.create_table(
        "koth_matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column("bracket", sa.Integer(), nullable=False),
        sa.Column(
            "game_mode", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column("num_teams", sa.Integer(), nullable=False),
        sa.Column("winner_team_number", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["koth_events.id"],
            name=op.f("fk_koth_matches_event_id_koth_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_koth_matches")),
        mysql_charset="utf8mb4",
    )
    op.create_table(
        "koth_signups",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("event_id", sa.Integer(), nullable=False),
        sa.Column(
            "twitch_username",
            sqlmodel.sql.sqltypes.AutoString(length=50),
            nullable=True,
        ),
        sa.Column(
            "battle_tag", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "w3c_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "race",
            sa.Enum("RANDOM", "HU", "OC", "NE", "UD", name="race"),
            nullable=False,
        ),
        sa.Column("mmr", sa.Integer(), nullable=False),
        sa.Column("bracket", sa.Integer(), nullable=False),
        sa.Column("is_king", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["koth_events.id"],
            name=op.f("fk_koth_signups_event_id_koth_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_koth_signups")),
        mysql_charset="utf8mb4",
    )
    op.create_table(
        "map_season",
        sa.Column("map_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["map_id"], ["maps.id"], name=op.f("fk_map_season_map_id_maps")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.id"], name=op.f("fk_map_season_season_id_seasons")
        ),
        sa.PrimaryKeyConstraint("map_id", "season_id", name=op.f("pk_map_season")),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("team1_id", sa.Integer(), nullable=False),
        sa.Column("team2_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("playday", sa.Integer(), nullable=False),
        sa.Column("team1_score", sa.Integer(), nullable=True),
        sa.Column("team2_score", sa.Integer(), nullable=True),
        sa.Column("fixed_map_id", sa.Integer(), nullable=True),
        sa.Column(
            "date_frame", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["fixed_map_id"], ["maps.id"], name=op.f("fk_matches_fixed_map_id_maps")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            ondelete="CASCADE",
            name=op.f("fk_matches_season_id_seasons"),
        ),
        sa.ForeignKeyConstraint(
            ["team1_id"],
            ["teams.id"],
            ondelete="CASCADE",
            name=op.f("fk_matches_team1_id_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["team2_id"],
            ["teams.id"],
            ondelete="CASCADE",
            name=op.f("fk_matches_team2_id_teams"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
    )
    op.create_table(
        "player_career_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "player_name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column("historical_rating", sa.Integer(), nullable=True),
        sa.Column("historical_series_won", sa.Integer(), nullable=True),
        sa.Column("historical_series_lost", sa.Integer(), nullable=True),
        sa.Column("historical_games_won", sa.Integer(), nullable=True),
        sa.Column("historical_games_lost", sa.Integer(), nullable=True),
        sa.Column("historical_seasons_played", sa.Integer(), nullable=True),
        sa.Column("rating", sa.Integer(), nullable=True),
        sa.Column("series_won", sa.Integer(), nullable=True),
        sa.Column("series_lost", sa.Integer(), nullable=True),
        sa.Column("series_winrate", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("games_won", sa.Integer(), nullable=True),
        sa.Column("games_lost", sa.Integer(), nullable=True),
        sa.Column("games_winrate", sa.DECIMAL(precision=5, scale=2), nullable=True),
        sa.Column("seasons_played", sa.Integer(), nullable=True),
        sa.Column(
            "avg_series_per_season", sa.DECIMAL(precision=5, scale=2), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="SET NULL",
            name=op.f("fk_player_career_stats_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_player_career_stats")),
        sa.UniqueConstraint(
            "player_name", name=op.f("uq_player_career_stats_player_name")
        ),
    )
    op.create_table(
        "team_season",
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("coach_1_id", sa.Integer(), nullable=True),
        sa.Column("coach_2_id", sa.Integer(), nullable=True),
        sa.Column("coach_3_id", sa.Integer(), nullable=True),
        sa.Column("final_score", sa.Integer(), nullable=True),
        sa.Column("points_available", sa.Integer(), nullable=True),
        sa.Column("points_against", sa.Integer(), nullable=True),
        sa.Column("maps_won", sa.Integer(), nullable=True),
        sa.Column("maps_lost", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["coach_1_id"], ["users.id"], name=op.f("fk_team_season_coach_1_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["coach_2_id"], ["users.id"], name=op.f("fk_team_season_coach_2_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["coach_3_id"], ["users.id"], name=op.f("fk_team_season_coach_3_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["season_id"], ["seasons.id"], name=op.f("fk_team_season_season_id_seasons")
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_season_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("team_id", "season_id", name=op.f("pk_team_season")),
    )
    op.create_table(
        "user_season_signup",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_user_season_signup_season_id_seasons"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_season_signup_user_id_users")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "season_id", name=op.f("pk_user_season_signup")
        ),
    )
    op.create_table(
        "user_team_season",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("team_id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("games", sa.Integer(), nullable=True),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("losses", sa.Integer(), nullable=True),
        sa.Column("matchup_history", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            name=op.f("fk_user_team_season_season_id_seasons"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_user_team_season_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_team_season_user_id_users")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "team_id", "season_id", name=op.f("pk_user_team_season")
        ),
    )
    op.create_table(
        "w3cstats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wc3_season", sa.Integer(), nullable=False),
        sa.Column("wins", sa.Integer(), nullable=True),
        sa.Column("losses", sa.Integer(), nullable=True),
        sa.Column("games", sa.Integer(), nullable=True),
        sa.Column("mmr", sa.Integer(), nullable=True),
        sa.Column("winrate", sa.Float(), nullable=True),
        sa.Column(
            "race",
            sa.Enum("RANDOM", "HU", "OC", "NE", "UD", name="race"),
            nullable=True,
        ),
        sa.Column("league", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_w3cstats_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_w3cstats")),
    )
    op.create_table(
        "draft_series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=True),
        sa.Column("caster", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("player1_id", sa.Integer(), nullable=False),
        sa.Column("player2_id", sa.Integer(), nullable=False),
        sa.Column("player1_score", sa.Integer(), nullable=True),
        sa.Column("player2_score", sa.Integer(), nullable=True),
        sa.Column("host_player_id", sa.Integer(), nullable=False),
        sa.Column("is_fantasy_match", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"], ["matches.id"], name=op.f("fk_draft_series_match_id_matches")
        ),
        sa.ForeignKeyConstraint(
            ["player1_id"], ["users.id"], name=op.f("fk_draft_series_player1_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"], ["users.id"], name=op.f("fk_draft_series_player2_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_draft_series")),
    )
    op.create_table(
        "fantasy_team_player",
        sa.Column("fantasy_team_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fantasy_team_id"],
            ["fantasy_teams.id"],
            name=op.f("fk_fantasy_team_player_fantasy_team_id_fantasy_teams"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_fantasy_team_player_user_id_users")
        ),
        sa.PrimaryKeyConstraint(
            "fantasy_team_id", "user_id", name=op.f("pk_fantasy_team_player")
        ),
    )
    op.create_table(
        "koth_match_participants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("signup_id", sa.Integer(), nullable=False),
        sa.Column("team_number", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["koth_matches.id"],
            name=op.f("fk_koth_match_participants_match_id_koth_matches"),
        ),
        sa.ForeignKeyConstraint(
            ["signup_id"],
            ["koth_signups.id"],
            name=op.f("fk_koth_match_participants_signup_id_koth_signups"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_koth_match_participants")),
        mysql_charset="utf8mb4",
    )
    op.create_table(
        "series",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column("date_time", sa.DateTime(), nullable=True),
        sa.Column("caster", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("player1_id", sa.Integer(), nullable=False),
        sa.Column("player2_id", sa.Integer(), nullable=False),
        sa.Column("player1_score", sa.Integer(), nullable=True),
        sa.Column("player2_score", sa.Integer(), nullable=True),
        sa.Column("player1_points", sa.Integer(), nullable=True),
        sa.Column("player2_points", sa.Integer(), nullable=True),
        sa.Column("host_player_id", sa.Integer(), nullable=False),
        sa.Column("is_fantasy_match", sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["matches.id"],
            ondelete="CASCADE",
            name=op.f("fk_series_match_id_matches"),
        ),
        sa.ForeignKeyConstraint(
            ["player1_id"],
            ["users.id"],
            ondelete="CASCADE",
            name=op.f("fk_series_player1_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["player2_id"],
            ["users.id"],
            ondelete="CASCADE",
            name=op.f("fk_series_player2_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_series")),
    )
    op.create_table(
        "fantasy_bets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("season_id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("winner_id", sa.Integer(), nullable=False),
        sa.Column("bet_points", sa.Integer(), nullable=False),
        sa.Column("bet_result", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["season_id"],
            ["seasons.id"],
            ondelete="CASCADE",
            name=op.f("fk_fantasy_bets_season_id_seasons"),
        ),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
            ondelete="CASCADE",
            name=op.f("fk_fantasy_bets_series_id_series"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="CASCADE",
            name=op.f("fk_fantasy_bets_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["winner_id"],
            ["users.id"],
            ondelete="CASCADE",
            name=op.f("fk_fantasy_bets_winner_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fantasy_bets")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fantasy_bets")
    op.drop_table("series")
    op.drop_table("koth_match_participants")
    op.drop_table("fantasy_team_player")
    op.drop_table("draft_series")
    op.drop_table("w3cstats")
    op.drop_table("user_team_season")
    op.drop_table("user_season_signup")
    op.drop_table("team_season")
    op.drop_table("player_career_stats")
    op.drop_table("matches")
    op.drop_table("map_season")
    op.drop_table("koth_signups")
    op.drop_table("koth_matches")
    op.drop_table("fantasy_teams")
    op.drop_table("users")
    op.drop_table("teams")
    op.drop_index(op.f("ix_settings_key"), table_name="settings")
    op.drop_table("settings")
    op.drop_table("seasons")
    op.drop_table("maps")
    op.drop_table("koth_events")
    # ### end Alembic commands ###
